### ISSUE TITLE
Best model weights

### ISSUE THREAD

**Issue by gmberton** [gastruc/osv5m#2]
Hi, thank you for the great work!
Regarding the best model you obtained, I see [here](https://github.com/gastruc/osv5m?tab=readme-ov-file#inference-) that you mention a "best model" and then the code refers to `Geolocalizer.from_pretrained('osv5m/baseline')`. Is the `Geolocalizer.from_pretrained('osv5m/baseline')` your best model, or is it just a baseline?

**Comment by gastruc** [comment]
Hi,
The model imported here is indeed the module corresponding to the best model.

**Comment by loicland** [comment]
To shed some lights on the nomenclature, our trained model is not designed to be an ultra-optimized geolocation framework, but a reasonable combination of existing computer vision modules (pretrained encoder, geolocation heads, contrastive losses etc). You can view it as a strong baseline that a dedicated geolocation model should be able to beat.

**Comment by gmberton** [comment]
This makes perfect sense, thank you both for your quick reply and interesting paper!
