### ISSUE TITLE
python files in datasets/ not included.

### ISSUE THREAD

**Issue by WouterButhker** [gastruc/osv5m#3]
Hi,

In DATASET.md the method load_dataset is referred to. However, this method is not included in this repository. Other files also try to import files and methods from datasets/ but it seems this folder is empty.

**Comment by gastruc** [comment]
Hi,
The line from datasets import load_dataset does not refer to a python script but to loading a function from the package datasets from huggingface. You can find its documentation here https://pypi.org/project/datasets/.
