### ISSUE TITLE
quadtree_10_1000.csv

### ISSUE THREAD

**Issue by GoodSMILE-BYTE** [gastruc/osv5m#4]
Hi，
I hope this email finds you well. I am trying to run the **train.py** script from your repository and encountered an error related to a **missing file: datasets/quadtree_10_1000.csv**. It seems that this file is not included in the repository, and I am unsure how to resolve this issue.

Could you kindly provide guidance on how to obtain or generate the **quadtree_10_1000.csv** file, or let me know if there is an alternative solution?

_Thank you for your time and for sharing this valuable work. I appreciate any assistance you can offer._

**Comment by nicolas-dufour** [comment]
Hi @GoodSMILE-BYTE ,
Thanks for taking interest in our project!
As stated in the ReadME, you should first preprocess the data running
```bash
python scripts/preprocessing/preprocess.py data_dir=datasets do_split=1000 #You will need to run this code with other splitting/depth arguments if you want to use different quadtree arguments
```

This should generate the quadtree and the associated csv.

If you just want to run inference, we've included the quadtree in the model released on HF, so it should work without this.

Hope this helps solve ur issue

**Comment by GoodSMILE-BYTE** [comment]
> Hi @GoodSMILE-BYTE , Thanks for taking interest in our project! As stated in the ReadME, you should first preprocess the data running
> 
> ```shell
> python scripts/preprocessing/preprocess.py data_dir=datasets do_split=1000 #You will need to run this code with other splitting/depth arguments if you want to use different quadtree arguments
> ```
> 
> This should generate the quadtree and the associated csv.
> 
> If you just want to run inference, we've included the quadtree in the model released on HF, so it should work without this.
> 
> Hope this helps solve ur issue

I wanted to express my gratitude for your helpful response to my task!

**Comment by GoodSMILE-BYTE** [comment]
Thank you for sharing . I'm trying to train the model with the provided 200GB train dataset, but my system's memory is limited. Can I use a smaller subset instead?

I encountered errors when training with a partial dataset. Any advice on whether the full dataset is essential or how to proceed with limited resources would be appreciated.

Best,
