### ISSUE TITLE
The runing sequence of the metadata preprocesssing code

### ISSUE THREAD

**Issue by GaoShuang98** [gastruc/osv5m#6]
Hi! great work! What is the runing sequence of the metadata preprocesssing code in the scsripts/preprocessing folder? Thank you!

**Comment by gastruc** [comment]
Hi,
For most applications, you just have to run preprocess.py. Other scripts are only here if you want to create your own quatrees.

**Comment by GaoShuang98** [comment]
Thank you for your response😁
